# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 07:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Codeset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeen', models.CharField(max_length=200)),
                ('codezh', models.CharField(max_length=200)),
                ('sina', models.CharField(max_length=200, null=True)),
                ('maincontract', models.CharField(max_length=200, null=True)),
                ('sbreed', models.CharField(max_length=200, unique=True)),
                ('nighttrade', models.BooleanField(default=True)),
                ('actived', models.BooleanField(default=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Marketurl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('1', 'SHANGHAI'), ('2', 'DALIAN'), ('3', 'ZHENGZHOU'), ('9', 'ZHONGJIN')], max_length=10)),
                ('market', models.IntegerField()),
                ('daily', models.CharField(max_length=200)),
                ('minute', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='codeset',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Marketurl'),
        ),
    ]
